### ISSUE TITLE
[BUG]: Payment date error: 'Invalid Date' when editing another day than creating

### ISSUE THREAD

**Issue by Tech6767** [AndresMorelos/Invoncify#81] opened 2022-06-04 22:17 UTC
**Describe the bug**
Small thing I just noticed:
When creating an invoice on day one and it is getting edited on day 2, if there was a payment date set to 10 days (probably others as well) it will show an error.

This happened, when I created an invoice at like 23:50 and edited it at 0:05 in the night. Suddenly the payment date was broken.

The creation date is the date of editing, which is fine (and correct), but I guess it is the source of the bug.

**To Reproduce**
1. Create an invoice
2. set payment date to 10 days 
3. edit the invoice a day later

**Expected behavior**
The date should be recalculated for the new creation date of the invoice.
example: First creation date: 4. June 22
payment date: 14. June 22
edited creation date: 5. June 22
payment date: 15. June 22
**Screenshots**

![image](https://user-images.githubusercontent.com/103525838/172027025-e7c937b5-bf2d-4b31-88e0-83ebd6f5dc3d.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 
 - Version 22.04

**Comment by AndresMorelos** [comment] 2022-06-05 18:03
@Tech6767 could you please share with me the invoncify version? I'm not able to reproduce it at the latest version.

**Comment by Tech6767** [comment] 2022-06-07 19:11
@AndresMorelos I will try again. I opened another invoice and will edit it tomorrow. If it does not happen again, I will close the issue. Thanks for trying.

**Comment by AndresMorelos** [comment] 2022-06-10 04:32
@Tech6767, did you reproduce the issue?

**Comment by Tech6767** [comment] 2022-06-10 17:23
@AndresMorelos I forgot about it...tried it now and yes, it still occurs: 
![image](https://user-images.githubusercontent.com/103525838/173118852-b25003d6-2499-4e9b-92e2-eeaf317b778b.png)

Maybe it needs to be in german? I entered more text in the payment details field, that's how it changes the creation date and then it messes up the 10 days due date.

**Comment by Tech6767** [comment] 2022-06-10 17:23
I can update the app and see if it still occurs?

**Comment by AndresMorelos** [comment] 2022-06-10 18:07
@Tech6767 yes, you can update the app, there is not problem.


I will setup your OS on a VM in order to test it.

**Comment by AndresMorelos** [comment] 2022-06-13 03:33
@Tech6767 I was able to reproduce the issue but without changing the Creation date, just selecting another due date term.

I'm working on this Right, the new versión of the app will be released soon with the fix. stay tunned.

**Closed** 2022-06-13 04:10 UTC
Labels: bug

**Comment by AndresMorelos** [comment] 2022-06-13 04:11
@Tech6767 Issue fix at v1.9.1, If the issue persists for you please reopen the issue and attach a video with your steps, the only way that I was able to reproduce it was without updating the creation date.
