### ISSUE TITLE
[BUG]: Huge performance issue

### ISSUE THREAD

**Issue by sonalder-darlene** [AndresMorelos/Invoncify#39] opened 2022-03-24 14:19 UTC
**Describe the bug**
The app is super laggy to use

**To Reproduce**
1. Open the app
2. Click on a section (contact, invoices, stats,settings)
3. The transition is not snappy at all

**Expected behavior**
The app use to be snappy and fast, now it feel laggy and slow :(

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [12.0.1]

**Comment by AndresMorelos** [comment] 2022-03-24 15:59
@sonalder-darlene could you please share with me the amount of invoices and contacts you have to make some performance testings in similar conditions?

**Comment by sonalder-darlene** [comment] 2022-03-24 16:02
Sure,
- 8 invoices
- 6 contacts
not that much as you can see

**Comment by AndresMorelos** [comment] 2022-04-03 06:13
@sonalder-darlene I tried to recreate the bad performance without success, do you have time to take a video of the behavior? I'm thinking to add some anon metrics to the app to measure those behaviors obviously with the opt-in selection to send that data

**Comment by sonalder-darlene** [comment] 2022-04-07 06:35
I started using it, how do I opt-in, my firewall ask for permission at start. Did you make it by default ?
Could you manage to make a checkbox in settings for auto-update by the way

**Comment by AndresMorelos** [comment] 2022-04-11 04:00
hey @sonalder-darlene, I just saw high times in the development stage of the app, I remember that you compile this app for Minecraft sound pack testing, could you please check if you're running the production version instead of the development one?

**Comment by AndresMorelos** [comment] 2022-04-12 15:06
@sonalder-darlene normally when we search for an application in the spotlight, if we wait some seconds a select dropdown is displayed showing file location when the tool detects two files with the same name, make sure to click on the app located in the application folder.


<img width="690" alt="image" src="https://user-images.githubusercontent.com/6563162/162993489-5f8fd39d-285d-4ede-80b8-219b94f495d3.png">

**Comment by AndresMorelos** [comment] 2022-04-14 16:14
@sonalder-darlene any update on this?

**Comment by AndresMorelos** [comment] 2022-04-16 01:05
@sonalder-darlene yes the telemetry opt-in checkbox is in the general settings tab, by default it is `On`, but I will do that, add it at the start up page.

**Comment by AndresMorelos** [comment] 2022-05-10 20:04
hey @sonalder-darlene I will close this issue since I'm not able to reproduce it or even see this performance issue in Sentry.

If you have more details to reproduce this issue fell free to open other one.

**Closed by AndresMorelos** 2022-05-10 20:04 UTC
Labels: bug, Mac
